# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_in'],
                'verbose_name': '\ube14\ub85c\uadf8 \ub0b4\uc6a9',
                'verbose_name_plural': '\ube14\ub85c\uadf8 \ub0b4\uc6a9\ub4e4',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': '\ube14\ub85c\uadf8 \uce74\ud14c\uace0\ub9ac',
                'verbose_name_plural': '\ube14\ub85c\uadf8 \uce74\ud14c\uace0\ub9ac\ub4e4',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='lecture.Subject'),
        ),
    ]
