# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:25
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20161201_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
