# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Rentalinventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rental.RentalCategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateTimeField(blank=True)),
                ('out_date', models.DateTimeField(blank=True)),
                ('status', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='account.Customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalinventory', to='rental.Rentalinventory')),
            ],
        ),
        migrations.AddField(
            model_name='rentalinventory',
            name='rentalproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalproduct', to='rental.RentalProduct'),
        ),
    ]
