# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='shop.Store'),
        ),
        migrations.AlterIndexTogether(
            name='rentalproduct',
            index_together=set([('id', 'slug')]),
        ),
    ]
