# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20161118_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='rentalcategory',
            table='RentalCategory',
        ),
        migrations.AlterModelTable(
            name='rentalinventory',
            table='Rentalinventory',
        ),
        migrations.AlterModelTable(
            name='rentalproduct',
            table='RentalProduct',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Reservation',
        ),
    ]
