# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20161122_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('in_date', 'status')},
        ),
    ]
